/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UnsubscribeEmailRouteImport } from './routes/unsubscribe-email'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SellersIdRouteImport } from './routes/sellers.$id'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminWalletsRouteImport } from './routes/admin.wallets'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTopupsRouteImport } from './routes/admin.topups'
import { Route as AdminThreadsRouteImport } from './routes/admin.threads'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminMaintenanceRouteImport } from './routes/admin.maintenance'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminInsightsRouteImport } from './routes/admin.insights'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminDebugRouteImport } from './routes/admin.debug'
import { Route as AdminCitiesRouteImport } from './routes/admin.cities'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBroadcastsRouteImport } from './routes/admin.broadcasts'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated.wallet'
import { Route as AuthenticatedVerifyRouteImport } from './routes/_authenticated.verify'
import { Route as AuthenticatedSavedSearchesRouteImport } from './routes/_authenticated.saved-searches'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedPostRouteImport } from './routes/_authenticated.post'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedMyListingsRouteImport } from './routes/_authenticated.my-listings'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated.messages'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated.favorites'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated.messages.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicSitemapDotxmlRouteImport } from './routes/api/public/sitemap[.]xml'
import { Route as ApiPublicClientErrorsRouteImport } from './routes/api/public/client-errors'
import { Route as ApiPublicAdminBootstrapRouteImport } from './routes/api/public/admin-bootstrap'
import { Route as AuthenticatedMessagesThreadIdRouteImport } from './routes/_authenticated.messages.$threadId'
import { Route as AuthenticatedDebugSessionRouteImport } from './routes/_authenticated.debug.session'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsNowpaymentsIpnRouteImport } from './routes/api/public/payments/nowpayments-ipn'
import { Route as ApiPublicCronMatchSavedSearchesRouteImport } from './routes/api/public/cron/match-saved-searches'
import { Route as ApiPublicCronAutoPromoteRouteImport } from './routes/api/public/cron/auto-promote'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeEmailRoute = UnsubscribeEmailRouteImport.update({
  id: '/unsubscribe-email',
  path: '/unsubscribe-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SellersIdRoute = SellersIdRouteImport.update({
  id: '/sellers/$id',
  path: '/sellers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTopupsRoute = AdminTopupsRouteImport.update({
  id: '/topups',
  path: '/topups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThreadsRoute = AdminThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDebugRoute = AdminDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCitiesRoute = AdminCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastsRoute = AdminBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVerifyRoute = AuthenticatedVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSavedSearchesRoute =
  AuthenticatedSavedSearchesRouteImport.update({
    id: '/saved-searches',
    path: '/saved-searches',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPostRoute = AuthenticatedPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyListingsRoute = AuthenticatedMyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapDotxmlRoute = ApiPublicSitemapDotxmlRouteImport.update({
  id: '/api/public/sitemap.xml',
  path: '/api/public/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClientErrorsRoute = ApiPublicClientErrorsRouteImport.update({
  id: '/api/public/client-errors',
  path: '/api/public/client-errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminBootstrapRoute = ApiPublicAdminBootstrapRouteImport.update({
  id: '/api/public/admin-bootstrap',
  path: '/api/public/admin-bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMessagesThreadIdRoute =
  AuthenticatedMessagesThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedDebugSessionRoute =
  AuthenticatedDebugSessionRouteImport.update({
    id: '/debug/session',
    path: '/debug/session',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsNowpaymentsIpnRoute =
  ApiPublicPaymentsNowpaymentsIpnRouteImport.update({
    id: '/api/public/payments/nowpayments-ipn',
    path: '/api/public/payments/nowpayments-ipn',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronMatchSavedSearchesRoute =
  ApiPublicCronMatchSavedSearchesRouteImport.update({
    id: '/api/public/cron/match-saved-searches',
    path: '/api/public/cron/match-saved-searches',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronAutoPromoteRoute =
  ApiPublicCronAutoPromoteRouteImport.update({
    id: '/api/public/cron/auto-promote',
    path: '/api/public/cron/auto-promote',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dmca': typeof DmcaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/unsubscribe-email': typeof UnsubscribeEmailRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/my-listings': typeof AuthenticatedMyListingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/post': typeof AuthenticatedPostRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved-searches': typeof AuthenticatedSavedSearchesRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/debug': typeof AdminDebugRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/threads': typeof AdminThreadsRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/listings/$id': typeof ListingsIdRoute
  '/sellers/$id': typeof SellersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/debug/session': typeof AuthenticatedDebugSessionRoute
  '/messages/$threadId': typeof AuthenticatedMessagesThreadIdRoute
  '/api/public/admin-bootstrap': typeof ApiPublicAdminBootstrapRoute
  '/api/public/client-errors': typeof ApiPublicClientErrorsRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/api/public/cron/auto-promote': typeof ApiPublicCronAutoPromoteRoute
  '/api/public/cron/match-saved-searches': typeof ApiPublicCronMatchSavedSearchesRoute
  '/api/public/payments/nowpayments-ipn': typeof ApiPublicPaymentsNowpaymentsIpnRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dmca': typeof DmcaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/unsubscribe-email': typeof UnsubscribeEmailRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/my-listings': typeof AuthenticatedMyListingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/post': typeof AuthenticatedPostRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved-searches': typeof AuthenticatedSavedSearchesRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/debug': typeof AdminDebugRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/threads': typeof AdminThreadsRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/listings/$id': typeof ListingsIdRoute
  '/sellers/$id': typeof SellersIdRoute
  '/admin': typeof AdminIndexRoute
  '/debug/session': typeof AuthenticatedDebugSessionRoute
  '/messages/$threadId': typeof AuthenticatedMessagesThreadIdRoute
  '/api/public/admin-bootstrap': typeof ApiPublicAdminBootstrapRoute
  '/api/public/client-errors': typeof ApiPublicClientErrorsRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/api/public/cron/auto-promote': typeof ApiPublicCronAutoPromoteRoute
  '/api/public/cron/match-saved-searches': typeof ApiPublicCronMatchSavedSearchesRoute
  '/api/public/payments/nowpayments-ipn': typeof ApiPublicPaymentsNowpaymentsIpnRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dmca': typeof DmcaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/unsubscribe-email': typeof UnsubscribeEmailRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/my-listings': typeof AuthenticatedMyListingsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/post': typeof AuthenticatedPostRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/saved-searches': typeof AuthenticatedSavedSearchesRoute
  '/_authenticated/verify': typeof AuthenticatedVerifyRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/debug': typeof AdminDebugRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/threads': typeof AdminThreadsRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/listings/$id': typeof ListingsIdRoute
  '/sellers/$id': typeof SellersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/debug/session': typeof AuthenticatedDebugSessionRoute
  '/_authenticated/messages/$threadId': typeof AuthenticatedMessagesThreadIdRoute
  '/api/public/admin-bootstrap': typeof ApiPublicAdminBootstrapRoute
  '/api/public/client-errors': typeof ApiPublicClientErrorsRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/api/public/cron/auto-promote': typeof ApiPublicCronAutoPromoteRoute
  '/api/public/cron/match-saved-searches': typeof ApiPublicCronMatchSavedSearchesRoute
  '/api/public/payments/nowpayments-ipn': typeof ApiPublicPaymentsNowpaymentsIpnRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/dmca'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/unsubscribe-email'
    | '/verify-email'
    | '/dashboard'
    | '/favorites'
    | '/messages'
    | '/my-listings'
    | '/notifications'
    | '/post'
    | '/profile'
    | '/saved-searches'
    | '/verify'
    | '/wallet'
    | '/admin/activity'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/broadcasts'
    | '/admin/categories'
    | '/admin/cities'
    | '/admin/debug'
    | '/admin/homepage'
    | '/admin/insights'
    | '/admin/kyc'
    | '/admin/listings'
    | '/admin/login'
    | '/admin/maintenance'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/threads'
    | '/admin/topups'
    | '/admin/users'
    | '/admin/wallets'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/listings/$id'
    | '/sellers/$id'
    | '/admin/'
    | '/debug/session'
    | '/messages/$threadId'
    | '/api/public/admin-bootstrap'
    | '/api/public/client-errors'
    | '/api/public/sitemap.xml'
    | '/lovable/email/suppression'
    | '/messages/'
    | '/api/public/cron/auto-promote'
    | '/api/public/cron/match-saved-searches'
    | '/api/public/payments/nowpayments-ipn'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/dmca'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/unsubscribe-email'
    | '/verify-email'
    | '/dashboard'
    | '/favorites'
    | '/my-listings'
    | '/notifications'
    | '/post'
    | '/profile'
    | '/saved-searches'
    | '/verify'
    | '/wallet'
    | '/admin/activity'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/broadcasts'
    | '/admin/categories'
    | '/admin/cities'
    | '/admin/debug'
    | '/admin/homepage'
    | '/admin/insights'
    | '/admin/kyc'
    | '/admin/listings'
    | '/admin/login'
    | '/admin/maintenance'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/threads'
    | '/admin/topups'
    | '/admin/users'
    | '/admin/wallets'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/listings/$id'
    | '/sellers/$id'
    | '/admin'
    | '/debug/session'
    | '/messages/$threadId'
    | '/api/public/admin-bootstrap'
    | '/api/public/client-errors'
    | '/api/public/sitemap.xml'
    | '/lovable/email/suppression'
    | '/messages'
    | '/api/public/cron/auto-promote'
    | '/api/public/cron/match-saved-searches'
    | '/api/public/payments/nowpayments-ipn'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/dmca'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/unsubscribe-email'
    | '/verify-email'
    | '/_authenticated/dashboard'
    | '/_authenticated/favorites'
    | '/_authenticated/messages'
    | '/_authenticated/my-listings'
    | '/_authenticated/notifications'
    | '/_authenticated/post'
    | '/_authenticated/profile'
    | '/_authenticated/saved-searches'
    | '/_authenticated/verify'
    | '/_authenticated/wallet'
    | '/admin/activity'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/broadcasts'
    | '/admin/categories'
    | '/admin/cities'
    | '/admin/debug'
    | '/admin/homepage'
    | '/admin/insights'
    | '/admin/kyc'
    | '/admin/listings'
    | '/admin/login'
    | '/admin/maintenance'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/threads'
    | '/admin/topups'
    | '/admin/users'
    | '/admin/wallets'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/listings/$id'
    | '/sellers/$id'
    | '/admin/'
    | '/_authenticated/debug/session'
    | '/_authenticated/messages/$threadId'
    | '/api/public/admin-bootstrap'
    | '/api/public/client-errors'
    | '/api/public/sitemap.xml'
    | '/lovable/email/suppression'
    | '/_authenticated/messages/'
    | '/api/public/cron/auto-promote'
    | '/api/public/cron/match-saved-searches'
    | '/api/public/payments/nowpayments-ipn'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DmcaRoute: typeof DmcaRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  UnsubscribeEmailRoute: typeof UnsubscribeEmailRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ListingsIdRoute: typeof ListingsIdRoute
  SellersIdRoute: typeof SellersIdRoute
  ApiPublicAdminBootstrapRoute: typeof ApiPublicAdminBootstrapRoute
  ApiPublicClientErrorsRoute: typeof ApiPublicClientErrorsRoute
  ApiPublicSitemapDotxmlRoute: typeof ApiPublicSitemapDotxmlRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicCronAutoPromoteRoute: typeof ApiPublicCronAutoPromoteRoute
  ApiPublicCronMatchSavedSearchesRoute: typeof ApiPublicCronMatchSavedSearchesRoute
  ApiPublicPaymentsNowpaymentsIpnRoute: typeof ApiPublicPaymentsNowpaymentsIpnRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe-email': {
      id: '/unsubscribe-email'
      path: '/unsubscribe-email'
      fullPath: '/unsubscribe-email'
      preLoaderRoute: typeof UnsubscribeEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sellers/$id': {
      id: '/sellers/$id'
      path: '/sellers/$id'
      fullPath: '/sellers/$id'
      preLoaderRoute: typeof SellersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/topups': {
      id: '/admin/topups'
      path: '/topups'
      fullPath: '/admin/topups'
      preLoaderRoute: typeof AdminTopupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/threads': {
      id: '/admin/threads'
      path: '/threads'
      fullPath: '/admin/threads'
      preLoaderRoute: typeof AdminThreadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maintenance': {
      id: '/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/debug': {
      id: '/admin/debug'
      path: '/debug'
      fullPath: '/admin/debug'
      preLoaderRoute: typeof AdminDebugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cities': {
      id: '/admin/cities'
      path: '/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AdminCitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcasts': {
      id: '/admin/broadcasts'
      path: '/broadcasts'
      fullPath: '/admin/broadcasts'
      preLoaderRoute: typeof AdminBroadcastsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/verify': {
      id: '/_authenticated/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthenticatedVerifyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/saved-searches': {
      id: '/_authenticated/saved-searches'
      path: '/saved-searches'
      fullPath: '/saved-searches'
      preLoaderRoute: typeof AuthenticatedSavedSearchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/post': {
      id: '/_authenticated/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof AuthenticatedPostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-listings': {
      id: '/_authenticated/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof AuthenticatedMyListingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap.xml': {
      id: '/api/public/sitemap.xml'
      path: '/api/public/sitemap.xml'
      fullPath: '/api/public/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/client-errors': {
      id: '/api/public/client-errors'
      path: '/api/public/client-errors'
      fullPath: '/api/public/client-errors'
      preLoaderRoute: typeof ApiPublicClientErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-bootstrap': {
      id: '/api/public/admin-bootstrap'
      path: '/api/public/admin-bootstrap'
      fullPath: '/api/public/admin-bootstrap'
      preLoaderRoute: typeof ApiPublicAdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/messages/$threadId': {
      id: '/_authenticated/messages/$threadId'
      path: '/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof AuthenticatedMessagesThreadIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/debug/session': {
      id: '/_authenticated/debug/session'
      path: '/debug/session'
      fullPath: '/debug/session'
      preLoaderRoute: typeof AuthenticatedDebugSessionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/nowpayments-ipn': {
      id: '/api/public/payments/nowpayments-ipn'
      path: '/api/public/payments/nowpayments-ipn'
      fullPath: '/api/public/payments/nowpayments-ipn'
      preLoaderRoute: typeof ApiPublicPaymentsNowpaymentsIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/match-saved-searches': {
      id: '/api/public/cron/match-saved-searches'
      path: '/api/public/cron/match-saved-searches'
      fullPath: '/api/public/cron/match-saved-searches'
      preLoaderRoute: typeof ApiPublicCronMatchSavedSearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/auto-promote': {
      id: '/api/public/cron/auto-promote'
      path: '/api/public/cron/auto-promote'
      fullPath: '/api/public/cron/auto-promote'
      preLoaderRoute: typeof ApiPublicCronAutoPromoteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesThreadIdRoute: typeof AuthenticatedMessagesThreadIdRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesThreadIdRoute: AuthenticatedMessagesThreadIdRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedMyListingsRoute: typeof AuthenticatedMyListingsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPostRoute: typeof AuthenticatedPostRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSavedSearchesRoute: typeof AuthenticatedSavedSearchesRoute
  AuthenticatedVerifyRoute: typeof AuthenticatedVerifyRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedDebugSessionRoute: typeof AuthenticatedDebugSessionRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedMyListingsRoute: AuthenticatedMyListingsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPostRoute: AuthenticatedPostRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSavedSearchesRoute: AuthenticatedSavedSearchesRoute,
  AuthenticatedVerifyRoute: AuthenticatedVerifyRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedDebugSessionRoute: AuthenticatedDebugSessionRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBroadcastsRoute: typeof AdminBroadcastsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCitiesRoute: typeof AdminCitiesRoute
  AdminDebugRoute: typeof AdminDebugRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminThreadsRoute: typeof AdminThreadsRoute
  AdminTopupsRoute: typeof AdminTopupsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminBroadcastsRoute: AdminBroadcastsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCitiesRoute: AdminCitiesRoute,
  AdminDebugRoute: AdminDebugRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminInsightsRoute: AdminInsightsRoute,
  AdminKycRoute: AdminKycRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminThreadsRoute: AdminThreadsRoute,
  AdminTopupsRoute: AdminTopupsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DmcaRoute: DmcaRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  UnsubscribeEmailRoute: UnsubscribeEmailRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ListingsIdRoute: ListingsIdRoute,
  SellersIdRoute: SellersIdRoute,
  ApiPublicAdminBootstrapRoute: ApiPublicAdminBootstrapRoute,
  ApiPublicClientErrorsRoute: ApiPublicClientErrorsRoute,
  ApiPublicSitemapDotxmlRoute: ApiPublicSitemapDotxmlRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicCronAutoPromoteRoute: ApiPublicCronAutoPromoteRoute,
  ApiPublicCronMatchSavedSearchesRoute: ApiPublicCronMatchSavedSearchesRoute,
  ApiPublicPaymentsNowpaymentsIpnRoute: ApiPublicPaymentsNowpaymentsIpnRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
